name: Trigger auto deployment for ppe-detection-api

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          acrName: acrppedetection1234  # Nom unique en minuscules/chiffres uniquement
          containerAppName: ppe-detection-api
          resourceGroup: rg-ppe-detection
          location: westeurope          # Région autorisée
          targetPort: 8000
