name: Sync to Hugging Face Spaces

on:
  push:
    branches: [ main ]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to hub
        env:
          pfa_token1: ${{ secrets.pfa_token1 }}
        run: git push --force https://Oumamach:$pfa_token1@huggingface.co/spaces/Oumamach/ppe-detection main
